### ISSUE TITLE
Switch from `pages` to `app` router

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/oso#96]
### Describe the feature you'd like to request

It's going to be unavoidable to want to do ISR + dynamic pages + fallback: blocking, so we mind as well switch.

### Describe the solution you'd like

Migrate to this
https://docs.plasmic.app/learn/nextjs-quickstart#framework=nextjs-app-dir

### Describe alternatives you've considered

Stay on the pages router

**Comment by ryscheng** [comment]
Maybe we're not ready for this yet

```
Error occurred prerendering page "/about". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Page with `dynamic = "error"` couldn't be rendered statically because it used `searchParams.toJSON`.
    at staticGenerationBailout (/home/ryscheng/git/github/hypercerts-org/oso/frontend/.next/server/chunks/523.js:98185:15)
    at Object.get (/home/ryscheng/git/github/hypercerts-org/oso/frontend/.next/server/chunks/523.js:98139:70)
    at stringify (<anonymous>)
    at pb (/home/ryscheng/git/github/hypercerts-org/oso/frontend/.next/server/chunks/523.js:99158:9)
    at mb (/home/ryscheng/git/github/hypercerts-org/oso/frontend/.next/server/chunks/523.js:99057:29)
    at Timeout._onTimeout (/home/ryscheng/git/github/hypercerts-org/oso/frontend/.next/server/chunks/523.js:98882:16)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
```

It works when you turn off `output: 'export'` in next.config.js, but it'd be nice to have that option

**Comment by ryscheng** [comment]
Done here:
https://github.com/hypercerts-org/oso/pull/128

The timing makes sense because we want dynamic pages like
- /project/slug
- /collection/slug

This confirms works with Plasmic dynamic page setup.
